export const REASONING_CONFIG = {
  COLD_START_MIN_CLAIMS: 6,
  MAX_CLAIMS_PER_SESSION: 200,
  SESSION_RETENTION_DAYS: 30,
  CAUTION_COOLDOWN_OBSERVES: 10,
  KUDOS_COOLDOWN_OBSERVES: 5,
  KUDOS_BIAS_WINDOW: 10,
  KUDOS_BIAS_CAUTION_THRESHOLD: 3,
  KUDOS_TIE_BREAK_WEIGHT: 0.4,
  LOAD_BEARING_MIN_DOWNSTREAM: 3,
  UNCHALLENGED_CHAIN_MIN_LENGTH: 4,
  ECHO_CHAMBER_MIN_SUPPORTS: 2,
  WELL_SOURCED_MIN_DOWNSTREAM: 3,
  PRODUCTIVE_STRESS_MIN_CHAIN: 3,
  GROUNDED_PREMISE_MIN_SUPPORTS: 2,
  MAX_CLAIM_TEXT_LENGTH: 240,
  RECENT_CLAIMS_CONTEXT: 10,
  DETECTOR_BUDGET_MS: 30
} as const
